# Site settings
title: Compound Fraxure
description: > # this means to ignore newlines until "baseurl:"
  The compoundest of fraxures
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://compoundfraxure.github.io" # the base hostname & protocol for your site
twitter_username: compoundfraxure
github_username:  compoundfraxure

# Build settings
markdown: redcarpet
pygments: true
paginate: 5
